import { defineConfig } from "vitepress";
import surqlGrammar from "./languages/surql.tmLanguage.json";

export default defineConfig({
	title: "Surqlize",
	titleTemplate: ":title | Surqlize",
	description:
		"A type-safe TypeScript ORM for SurrealDB, with automatic schema migrations.",

	// Force dark mode only (no toggle)
	appearance: "force-dark",

	// Canonical URL for SEO
	base: "/",

	// Sitemap generation
	sitemap: {
		hostname: "https://surqlize.com",
	},

	// Clean URLs (no .html extension)
	cleanUrls: true,

	// No "last updated" line. It is read from the git history, so a whitespace
	// fix reads as the page having changed — which is worse than no date at all
	// on reference pages people return to.
	lastUpdated: false,

	markdown: {
		languages: [
			{
				...surqlGrammar,
				aliases: ["surql", "surrealql", "surrealdb"],
			},
		],
	},

	head: [
		// Favicon
		[
			"link",
			{
				rel: "icon",
				href: "/assets/surqlize-favicon.svg",
				type: "image/svg+xml",
			},
		],
		["link", { rel: "icon", href: "/favicon.ico", sizes: "32x32" }],

		// Open Graph / Facebook
		["meta", { property: "og:type", content: "website" }],
		["meta", { property: "og:site_name", content: "Surqlize" }],
		[
			"meta",
			{
				property: "og:title",
				content: "Surqlize — A type-safe TypeScript ORM for SurrealDB",
			},
		],
		[
			"meta",
			{
				property: "og:description",
				content:
					"One schema definition, used twice: a fully typed query builder, and migrations generated by comparing that schema against your database.",
			},
		],
		[
			"meta",
			{
				property: "og:image",
				content: "https://surqlize.com/assets/surqlize-og-image.webp",
			},
		],
		["meta", { property: "og:image:width", content: "1200" }],
		["meta", { property: "og:image:height", content: "630" }],
		[
			"meta",
			{
				property: "og:image:alt",
				content: "Surqlize — A type-safe TypeScript ORM for SurrealDB",
			},
		],
		["meta", { property: "og:locale", content: "en_US" }],

		// Twitter Card
		["meta", { name: "twitter:card", content: "summary_large_image" }],
		[
			"meta",
			{
				name: "twitter:title",
				content: "Surqlize — A type-safe TypeScript ORM for SurrealDB",
			},
		],
		[
			"meta",
			{
				name: "twitter:description",
				content:
					"One schema definition, used twice: a fully typed query builder, and automatic schema migrations.",
			},
		],
		[
			"meta",
			{
				name: "twitter:image",
				content: "https://surqlize.com/assets/surqlize-og-image.webp",
			},
		],
		[
			"meta",
			{
				name: "twitter:image:alt",
				content: "Surqlize — A type-safe TypeScript ORM for SurrealDB",
			},
		],

		// Additional SEO
		["meta", { name: "author", content: "SurrealDB" }],
		[
			"meta",
			{
				name: "keywords",
				content:
					"SurrealDB, TypeScript ORM, type inference, query builder, database migrations, schema management, SurrealQL, graph database, vector database, live queries",
			},
		],
		["meta", { name: "robots", content: "index, follow" }],
		["meta", { name: "googlebot", content: "index, follow" }],

		// Theme color for mobile browsers
		["meta", { name: "theme-color", content: "#0b0b0d" }],

		// Apple touch icon
		["link", { rel: "apple-touch-icon", href: "/assets/surqlize-favicon.svg" }],
	],

	themeConfig: {
		logo: {
			src: "/assets/surqlize-logo-dark.svg",
			alt: "surqlize logo with a lightning bolt icon",
		},
		siteTitle: false,

		nav: [
			{ text: "Guide", link: "/guide/" },
			{ text: "Schema", link: "/schema/" },
			{ text: "Migrations", link: "/migrations/" },
			{ text: "ORM", link: "/orm/" },
			{
				text: "Links",
				items: [
					{ text: "GitHub", link: "https://github.com/surrealdb/surqlize" },
					{ text: "npm", link: "https://www.npmjs.com/package/surqlize" },
					{
						text: "Changelog",
						link: "https://github.com/surrealdb/surqlize/blob/main/CHANGELOG.md",
					},
					{ text: "SurrealDB", link: "https://surrealdb.com/" },
				],
			},
		],

		sidebar: {
			"/guide/": [
				{ text: "Guide", items: [{ text: "Overview", link: "/guide/" }] },
			],
			"/schema/": [
				{ text: "Schema", items: [{ text: "Overview", link: "/schema/" }] },
			],
			"/migrations/": [
				{
					text: "Migrations",
					items: [{ text: "Overview", link: "/migrations/" }],
				},
			],
			"/orm/": [{ text: "ORM", items: [{ text: "Overview", link: "/orm/" }] }],
		},

		socialLinks: [
			{ icon: "github", link: "https://github.com/surrealdb/surqlize" },
		],

		footer: {
			message: "Released under the Apache 2.0 License.",
			copyright: "Copyright © 2026 SurrealDB",
		},

		search: {
			provider: "local",
		},

		editLink: {
			pattern: "https://github.com/surrealdb/surqlize/edit/main/docs/:path",
			text: "Edit this page on GitHub",
		},

		outline: {
			level: [2, 3],
			label: "On this page",
		},
	},

	// Dynamic page-level SEO
	transformPageData(pageData) {
		const canonicalUrl = `https://surqlize.com/${pageData.relativePath}`
			.replace(/index\.md$/, "")
			.replace(/\.md$/, "");

		pageData.frontmatter.head ??= [];
		pageData.frontmatter.head.push([
			"link",
			{ rel: "canonical", href: canonicalUrl },
		]);

		// Dynamic Open Graph URL per page
		pageData.frontmatter.head.push([
			"meta",
			{ property: "og:url", content: canonicalUrl },
		]);
	},
});
